"""fix_Unicode_third_try

Revision ID: 48ec3613abcd
Revises: 725e6d32fe89
Create Date: 2025-03-14 16:24:18.805081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '48ec3613abcd'
down_revision: Union[str, None] = '725e6d32fe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forms', 'fields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),  # Исправлено здесь
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forms', 'fields',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###