"""fix_Unicode_second_try

Revision ID: 725e6d32fe89
Revises: 27857a7591fb
Create Date: 2025-03-14 14:47:47.629676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725e6d32fe89'
down_revision: Union[str, None] = '27857a7591fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
