"""add_Form_Answers_User

Revision ID: 996ac0dfc6d6
Revises: c6c22dc27e51
Create Date: 2025-03-10 21:09:16.000818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996ac0dfc6d6'
down_revision: Union[str, None] = 'c6c22dc27e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
