"""fix_access_token

Revision ID: a8a205840d7d
Revises: 232c39ca89e7
Create Date: 2025-03-11 17:31:53.147727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8a205840d7d"
down_revision: Union[str, None] = "232c39ca89e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "access_token", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "access_token", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
