"""fix_db

Revision ID: e68dd3fc62a0
Revises: b7355fb5f4d4
Create Date: 2025-03-10 18:30:20.482515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e68dd3fc62a0"
down_revision: Union[str, None] = "b7355fb5f4d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
